const enc=new TextEncoder(); const dec=new TextDecoder();
const json=(obj,status=200,extra={})=>new Response(JSON.stringify(obj),{status,headers:{'Content-Type':'application/json',...extra}});
function cors(env,req){let o=req.headers.get('Origin')||'';let allowed=(env.ALLOWED_ORIGINS||'').split(',').map(x=>x.trim());return allowed.includes(o)?{'Access-Control-Allow-Origin':o,'Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Vary':'Origin'}:{}}
function b64url(bytes){return btoa(String.fromCharCode(...new Uint8Array(bytes))).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')}
function fromb64(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function hmac(secret,msg){let key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return crypto.subtle.sign('HMAC',key,enc.encode(msg))}
async function jwt(env,payload){let h=b64url(enc.encode(JSON.stringify({alg:'HS256',typ:'JWT'})));let p=b64url(enc.encode(JSON.stringify({...payload,exp:Math.floor(Date.now()/1000)+60*60*24*30})));let s=b64url(await hmac(env.JWT_SECRET,h+'.'+p));return h+'.'+p+'.'+s}
async function verifyJwt(env,t){try{let [h,p,s]=t.split('.');let want=b64url(await hmac(env.JWT_SECRET,h+'.'+p));if(want!==s)return null;let x=JSON.parse(dec.decode(fromb64(p)));return x.exp>Date.now()/1000?x:null}catch{return null}}
async function passwordHash(pw,salt){let key=await crypto.subtle.importKey('raw',enc.encode(pw),'PBKDF2',false,['deriveBits']);let bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:fromb64(salt),iterations:150000,hash:'SHA-256'},key,256);return b64url(bits)}
function bearer(req){let h=req.headers.get('Authorization')||'';return h.startsWith('Bearer ')?h.slice(7):''}
async function user(req,env){let p=await verifyJwt(env,bearer(req));if(!p)return null;return env.DB.prepare('SELECT id,email,name,plan FROM users WHERE id=?').bind(p.uid).first()}
async function body(req){return req.json().catch(()=>({}))}
async function stripe(env,path,params){let r=await fetch('https://api.stripe.com/v1/'+path,{method:'POST',headers:{Authorization:'Bearer '+env.STRIPE_SECRET_KEY,'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(params)});let j=await r.json();if(!r.ok)throw new Error(j.error?.message||'Stripe error');return j}
async function verifyStripe(req,env,raw){let sig=req.headers.get('Stripe-Signature')||'';let parts=Object.fromEntries(sig.split(',').map(x=>x.split('=')));if(!parts.t||!parts.v1)return false;let want=b64url(await hmac(env.STRIPE_WEBHOOK_SECRET,parts.t+'.'+raw));let hex=[...new Uint8Array(await hmac(env.STRIPE_WEBHOOK_SECRET,parts.t+'.'+raw))].map(b=>b.toString(16).padStart(2,'0')).join('');return hex===parts.v1}
export default {async fetch(req,env){let C=cors(env,req);if(req.method==='OPTIONS')return new Response(null,{headers:C});let u=new URL(req.url);try{
 if(u.pathname==='/api/health')return json({ok:true},200,C);
 if(u.pathname==='/api/leads'&&req.method==='POST'){let b=await body(req),email=String(b.email||'').trim().toLowerCase();if(!email.includes('@'))return json({error:'Valid email required'},400,C);await env.DB.prepare('INSERT OR IGNORE INTO leads(email,source,created_at) VALUES(?,?,?)').bind(email,String(b.source||''),new Date().toISOString()).run();return json({ok:true},200,C)}
 if(u.pathname==='/api/signup'&&req.method==='POST'){let b=await body(req),email=String(b.email||'').trim().toLowerCase(),name=String(b.name||'').trim(),pw=String(b.password||'');if(!email.includes('@')||name.length<2||pw.length<8)return json({error:'Name, valid email and 8+ character password required'},400,C);let salt=b64url(crypto.getRandomValues(new Uint8Array(16))),hash=await passwordHash(pw,salt);let r=await env.DB.prepare('INSERT INTO users(email,name,password_hash,salt,created_at) VALUES(?,?,?,?,?)').bind(email,name,hash,salt,new Date().toISOString()).run().catch(()=>null);if(!r?.success)return json({error:'That email is already registered'},409,C);let row=await env.DB.prepare('SELECT id,email,name,plan FROM users WHERE email=?').bind(email).first();return json({token:await jwt(env,{uid:row.id}),user:row},200,C)}
 if(u.pathname==='/api/login'&&req.method==='POST'){let b=await body(req),email=String(b.email||'').trim().toLowerCase(),pw=String(b.password||''),row=await env.DB.prepare('SELECT * FROM users WHERE email=?').bind(email).first();if(!row||await passwordHash(pw,row.salt)!==row.password_hash)return json({error:'Invalid email or password'},401,C);return json({token:await jwt(env,{uid:row.id}),user:{id:row.id,email:row.email,name:row.name,plan:row.plan}},200,C)}
 if(u.pathname==='/api/me'){let me=await user(req,env);return me?json({user:me},200,C):json({error:'Unauthorized'},401,C)}
 if(u.pathname==='/api/watchlist'){let me=await user(req,env);if(!me)return json({error:'Sign in required'},401,C);if(req.method==='GET'){let r=await env.DB.prepare('SELECT ticker,created_at FROM watchlist WHERE user_id=? ORDER BY created_at DESC').bind(me.id).all();return json({items:r.results},200,C)}if(req.method==='POST'){let b=await body(req),t=String(b.ticker||'').toUpperCase().replace(/[^A-Z0-9.-]/g,'').slice(0,8);if(!t)return json({error:'Ticker required'},400,C);await env.DB.prepare('INSERT OR IGNORE INTO watchlist(user_id,ticker,created_at) VALUES(?,?,?)').bind(me.id,t,new Date().toISOString()).run();return json({ok:true},200,C)}}
 if(u.pathname.startsWith('/api/rankings/')){let me=await user(req,env);if(!me||!['pro','premium'].includes(me.plan))return json({error:'Pro membership required'},403,C);let slug=u.pathname.split('/').pop(),r=await env.DB.prepare('SELECT * FROM rankings WHERE slug=?').bind(slug).first();return r?json({slug,updated_at:r.updated_at,items:JSON.parse(r.data_json)},200,C):json({error:'Ranking unavailable'},404,C)}
 if(u.pathname==='/api/admin/sync-ranking'&&req.method==='POST'){if(bearer(req)!==env.SYNC_TOKEN)return json({error:'Forbidden'},403,C);let b=await body(req);await env.DB.prepare('INSERT INTO rankings(slug,updated_at,data_json) VALUES(?,?,?) ON CONFLICT(slug) DO UPDATE SET updated_at=excluded.updated_at,data_json=excluded.data_json').bind(b.slug,b.updated_at,JSON.stringify(b.items||[])).run();return json({ok:true},200,C)}
 if(u.pathname==='/api/admin/sync-stocks'&&req.method==='POST'){if(bearer(req)!==env.SYNC_TOKEN)return json({error:'Forbidden'},403,C);let b=await body(req),now=new Date().toISOString();for(let x of (b.stocks||[])){await env.DB.prepare('INSERT INTO stocks(ticker,updated_at,data_json) VALUES(?,?,?) ON CONFLICT(ticker) DO UPDATE SET updated_at=excluded.updated_at,data_json=excluded.data_json').bind(x.ticker,now,JSON.stringify(x)).run()}return json({ok:true},200,C)}
 if(u.pathname==='/api/create-checkout-session'&&req.method==='POST'){if(env.PAYMENTS_ENABLED!=='true')return json({error:'Payments are not enabled yet'},503,C);let me=await user(req,env);if(!me)return json({error:'Sign in required'},401,C);let b=await body(req),price=b.plan==='premium'?env.STRIPE_PRICE_PREMIUM:env.STRIPE_PRICE_PRO;let s=await stripe(env,'checkout/sessions',{'mode':'subscription','line_items[0][price]':price,'line_items[0][quantity]':'1','customer_email':me.email,'client_reference_id':String(me.id),'metadata[plan]':String(b.plan==='premium'?'premium':'pro'),'success_url':(env.SITE_URL||'https://smarttrades.ai')+'/watchlist/?checkout=success','cancel_url':(env.SITE_URL||'https://smarttrades.ai')+'/pricing/'});return json({url:s.url},200,C)}
 if(u.pathname==='/api/stripe-webhook'&&req.method==='POST'){let raw=await req.text();if(!await verifyStripe(req,env,raw))return new Response('bad signature',{status:400});let ev=JSON.parse(raw);if(ev.type==='checkout.session.completed'){let o=ev.data.object,id=+o.client_reference_id;let plan=(o.metadata?.plan==='premium'?'premium':'pro');await env.DB.prepare('UPDATE users SET plan=?,stripe_customer_id=? WHERE id=?').bind(plan,o.customer,id).run()}return new Response('ok')}
 return json({error:'Not found'},404,C)
 }catch(e){return json({error:e.message||'Server error'},500,C)}}}
