CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT UNIQUE NOT NULL,name TEXT NOT NULL,password_hash TEXT NOT NULL,salt TEXT NOT NULL,plan TEXT NOT NULL DEFAULT 'free',stripe_customer_id TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS leads (id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT UNIQUE NOT NULL,source TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS watchlist (user_id INTEGER NOT NULL,ticker TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(user_id,ticker));
CREATE TABLE IF NOT EXISTS rankings (slug TEXT PRIMARY KEY,updated_at TEXT NOT NULL,data_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS stocks (ticker TEXT PRIMARY KEY,updated_at TEXT NOT NULL,data_json TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
